### ISSUE TITLE
Criar documento do `5W2H`

### ISSUE THREAD

**Issue by KiSobral** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#1]
Deve ser produzido o artefato referente ao 5W2H.

**Comment by KiSobral** [comment]
O responsável por revisar a issue e realizar a junção de todos os 5W2H em um geral foi o @Rafaelltm

**Comment by LeoSilvaGomes** [comment]
# 5W2H Leonardo

> 5W2H para entendimento do produto

## What
Um aplicativo de acompanhamento da saúde e rotina do Pet

## Why
Para acompanhar o andamento das atividades do animal, como ida ao veterinário, medicamentos, peso, altura, dentre outras coisas.

## Where
Esse aplicativo será desenvolvido para celular, pois tem o uso do celular tende a ser de mais fácil acesso do que um computador. Por isso a decisão do desenvolvimento de um aplicativo é umas das partes primordiais do projeto

## When
Poderá ser usado a qualquer momento! 

## Who
O principal usuário do aplicativo será os donos de Pet, mas poderá ser usado para hosteis de pets, adestradores, dentre outros que estarão envolvidos diretamente no cuidado com o animal.

## How much
Será disponibilizado de graça

## How
O aplicativo será disponibilizado na PlayStore (Android) ou na AppleStore (IOS).

---

> 5W2H para entendimento de desenvolvimento do produto

## What 
Desenvolvimento de um aplicativo de acompanhamento da saúde e rotina do Pet

## Why
Para fornecer uma melhor interface e conforto de acompanhamento para os envolvidos na saúde e rotina de pets. 

## Where 
Esse aplicativo será desenvolvido na disciplina de Arquitetura e Desenho de Software da Universidade de Brasília do curso eengenharia de software

## When
Durante o primeiro semestre de 2021 do ano letivo da Universidade de Brasília, pois é neste semestre que os membros do Grupo 1 da disciplina Arquitetura e Desenho de Software estarão dedicados ao desenvolvimento do projeto.

## Who
Os integrantes do Grupo 1 da disciplina Arquitetura e Desenho de Software, que é composto por 8 membros da turma do curso. Todos os membros da equipe fazem engenharia de software na UnB.

## How much
O custo do projeto é estimado com o tempo gasto pelos alunos para o desenvolvimento do mesmo.

## How
Utilizando plataforma de gerencimaneto de equipe, versionamento de projeto e metologias aprendidas durante o curso de engenharia de software da UnB

**Comment by KiSobral** [comment]
# 5W2H do Hugo
## What
O app Animalesco. O Animalesco é um app mobile que concentra suas funcionalidades no auxílio para com a saúde e cuidado dos pets aos seus donos, isto é, gerenciamento do calendário de medicações e vacinas do pet; controle de visitas ao veterinário/petshop; acompanhamento de peso e bem estar; entre outras possibilidades para se realizar dentro do app. 

## Why
Para facilitar os cuidados com o pet a partir de uma interface próxima e amigável às pessoas do século XXI, isto é, por meio de uma solução em software para smartphones.

## Where
O app pode ser encontrado nas principais lojas de distribuição de aplicativos de 2021 (Google Play e App Store).

## When
O app deve estar disponível 24/7.
Não somente em questão de "quando está disponível", o projeto será realizado no primeiro semestre letivo do calendário acadêmico de 2021 da UnB.

## Who
O app será desenvolvido por uma equipe de 8 integrantes, todos graduandos em engenharia de software e que estejam cursando a disciplina de Arquitetura e Desenho de Software.
O app se destina aos pais de pet que busquem manter o controle da saúde do seu pet.

## How
O projeto será desenvolvido por meio de metodologias ágeis e seguirá diretrizes já consolidadas para a construção de boas soluções computacionais, isto é, padrões de projeto bem definidos.

## How much
O custo do projeto envolve os gastos pessoais de cada integrante da equipe de desenvolvimento durante o período de trabalho para o projeto. Deste forma, enquadram-se os custos de:
- energia
- alimentação
- custos operacionais com computadores para o desenvolvimento
Além disso, observa-se a taxa de disponibilização do app nas lojas de distribuição.

**Comment by JoaoVitorFarias** [comment]
# 5W2H do João Vitor

## What
Uma aplicação mobile que irá auxiliar no acompanhamento da saúde do pet.

## Why
Para centralizar as informações sobre o pet, de forma que facilite os cuidados com o mesmo.

## Where
Brasília-DF.

## When 
Entre julho de 2021 até novembro de 2021, período correspondente ao 1° semestre letivo de 2021 da UnB.

## Who 
O público alvo do aplicativo são os donos de pets.

## How
Uso de metodologias ágeis e desenvolvimento do aplicativo.

## How much
O custo é estabelecido pelo tempo de dedicação dos membros da equipe no desenvolvimento do projeto.

**Comment by lorranyoliveira** [comment]
# 5W2H da Lorrany

## What
Um aplicativo chamado animalesco que tem como objetivo você administrar os cuidados com o seu pet.

## Why
Para você ter mais praticidade em acompanhar:
-  Vacinações
-  Cuidados com a higiene do seu pet
-  Idas ao veterinário
- Controle de medicamento

## Where 
Será feito em Brasília-DF.

## When
O aplicativo será desenvolvido durante o semestre 1°/2021. 

## Who
O aplicativo será desenvolvido pelo equipe animalesco, composto por 8 estudantes do curso de engenharia de software da Universidade de Brasília.

## How
Será desenvolvido por meio de metodologias e tecnologias escolhidas pela equipe.

## How much
Irá custar esforço e tempo dos estudantes.

**Comment by daniso123** [comment]
# 5W2H da Daniela 
## What
Criação do aplicativo Animalesco, que vai acompanhar a agenda do Pet.

## Why
Para facilitar o acompanhamento e os cuidados com o animal, como banho, remédios, idas ao veterinário dentre outras.

## Where
O aplicativo mobile será desenvolvido na disciplina de Arquitetura e Desenho de Software da Universidade de Brasília.

## When
Durante o semestre da matéria, primeiro semestre de 2021.

## Who
Os integrantes do grupo 1 da disciplina, que composto por 8 integrantes.

## How

Será desenvolvido por meio de metodologias ágeis, metodologias aprendidas na materia e tecnologias para o desenvolvimento técnico do projeto.

## How much
Custo médio do projeto é calculado com o tempo gasto pelos alunos.

**Comment by viniciusoliveira96** [comment]
#5W2H do Vinicius

##What
Criação de um app que que tem como objetivo facilitar que o dono do Pet tenha os cuidados necessários e/ou agendar acompanhar a agenda do mesmo. 

##Why
Para acompanhar toda a vida do Pet, como idas ao veterinario, vacinas tomadas e a tomar, cuidados com higiene dentre outros.

##Where
Ele será disponibilizado nas lojas de aplicativos para smartphones.

##When
O mesmo será desenvolvido na disciplina de Arquitetura e Desenho de Software no primeiro semestre de 2021

##Who
Todos os integrantes do grupo 1 da disciplina.

##How
O desenvolvimento será por meio de tecnologias ágeis como também tecnologias que o grupo irá propor.

##How Much
O custo total será calculado pelo tempo médio gasto dos integrantes, porém o App será disponibilizado de forma gratuita.
