### ISSUE TITLE
Criar o documento `Mapa mental` 

### ISSUE THREAD

**Issue by daniso123** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#10]
Criar mapa mental para licitação de requisitos

**Comment by LeoSilvaGomes** [comment]
A partir de uma reunião feita pelo Teams, foi feito um brainstorm e o levantamento de várias preocupações acerca do projeto e visões iniciais de coisas que iremos enfrentar durante o projeto.

**Comment by LeoSilvaGomes** [comment]
O primeiro `mapa mental` é relacionado a visão geral do projeto! Onde durante o levantamento de ideias foi possível identificar os principais tópicos:  

![image](https://user-images.githubusercontent.com/61520601/127411900-b33afb31-ce56-4ccd-90e6-9878737a8f55.png)

**Comment by LeoSilvaGomes** [comment]
O segundo `mapa mental` está relacionado ao desenvolvimento da equipe no projeto. Esse mapa mental é mais simplista, trazendo aspectos generalistas no que diz respeito a:
- Metodologia
- Tecnologias gerenciamento
- Fases do projeto

O mapa mental pode ser visto abaixo para mais detalhe.

![image](https://user-images.githubusercontent.com/61520601/127412137-8128939e-82fd-4fae-a475-ce40c6b10b11.png)
