### ISSUE TITLE
Criação do repositório front-end

### ISSUE THREAD

**Issue by KiSobral** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#104]
## Descrição
Esta issue engloba a criação do repositório destinado ao código do front-end da aplicação

## Critérios de Aceitação:
- [ ] O repositório deve estar disponível, de modo público, na organização de desenho
- [ ] O repositório já deve estar com a tecnologia acordada para o front-end
- [ ] O repositório deve estar com a ferramenta expo configurada

## Tarefas
- [x] Criar o repositório
- [x] Inicializar um projeto dentro do repositório
- [ ]  Adicionar as pastas que já foram decididas no diagrama de pacotes

**Comment by Rafaelltm** [comment]
@daniso123 Foi feita a criação das pastas de acordo com o diagrama de pacotes, porém o github não contabiliza pastas vazias como alteração. Por isso, no repositório só será possível ver que foi criada a pasta "src" e dentro dela o arquivo "routes.js".

**Comment by Rafaelltm** [comment]
Apesar da issue fechada, ainda no dia de hoje(entrega da issue) subimos as pastas vazias da estrutura com o uso do .gitkeep
