### ISSUE TITLE
Criação do cadastro do usuário 

### ISSUE THREAD

**Issue by daniso123** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#107]
## Descrição
Eu como usuário desejo poder realizar cadastro para ter acesso a aplicação

## Critérios de Aceitação:

- [x] Criação de componentes na aplicação
- [ ] Pagina de cadastro criada 
- [x] Utilização da paleta de cores escolhida 
- [ ] Requisição POST funcionando 
- [ ] Model de usuário
- [ ] Endpoint para registro de novos usuários

## Tarefas:

- [x] Criar model de usuário
- [x] Disponibilizar endpoint para registro de novos usuários
- [ ] Criar página de cadastro
- [ ] Implementar service de requisição POST para usuário

**Comment by KiSobral** [comment]
A pontuação dada para a issue foi de 13
![image](https://user-images.githubusercontent.com/43852963/131423059-d0a16ee9-7ee2-411f-af14-db3378fbacc9.png)
