### ISSUE TITLE
Criação do login da aplicação

### ISSUE THREAD

**Issue by daniso123** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#109]
## Descrição

Eu como usuário desejo realizar login para ter acesso ao app

## Critérios de Aceitação:

- [ ] Autenticação de usuário funcionando
- [ ] Página de login criada
- [ ] Requisição POST criada e funcionando
- [ ] Token de autenticação do usuário localmente e funcionando 

## Tarefas:

- [ ] Disponibilizar endpoint de autenticação de usuário
- [x] Criar página de login
- [ ] Implementar da service de requisição POST para login
- [ ] Armazenar de maneira local o token de autenticação do usuário

**Comment by KiSobral** [comment]
A pontuação dada para a issue foi de 13
![image](https://user-images.githubusercontent.com/43852963/131423146-c38df515-1e38-4242-bcad-0efb95e1e37c.png)

**Comment by LeoSilvaGomes** [comment]
A gente desenvolveu muito bem a parte do front da issue:
- A gente criou a função para receber a api
- Criamos toda a visualização
- Estruturamos as imagens padrões

![photo_2021-09-06_20-09-20](https://user-images.githubusercontent.com/61520601/132264973-9d878d59-39fb-4027-964f-3733d2ebd509.jpg)
