### ISSUE TITLE
Criação de cadastro do(s) pet(s)

### ISSUE THREAD

**Issue by daniso123** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#112]
## Descrição

Eu como usuário desejo poder cadastrar meu(s) pet(s) na aplicação para realizar o controle das informações dele(s)

## Critérios de Aceitação:

- [ ] Criação de componentes na aplicação
- [ ] Pagina de cadastro de pet criada 
- [ ] Utilização da paleta de cores escolhida 
- [ ] Requisição POST funcionando 
- [ ] Model de pet

## Tarefas:

- [ ] Criar model de pet
- [ ] Disponibilizar endpoint para registro de novos pets
- [ ] Criar página de cadastro de pet
- [ ] Implementar service de requisição POST para pets

**Comment by KiSobral** [comment]
A pontuação dada para a issue foi de 8
![image](https://user-images.githubusercontent.com/43852963/132266854-17cba486-ba13-4456-8347-a1fc86ebed60.png)
