### ISSUE TITLE
Registros de banhos do(s) pet(s)

### ISSUE THREAD

**Issue by daniso123** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#115]
## Descrição

Eu com usuário desejo poder registrar os banhos do(s) meu(s) pet(s) para manter o controle

## Critérios de Aceitação:

- [ ]  service de requisição POST criado e funcionando
- [ ] Cadastro de banho criado e funcionando 

## Tarefas:

- [ ] Criar model de banho
- [ ] Disponibilizar endpoint para registro de novos banhos a determinado pet
- [ ] Criar visualização de cadastro de banho.
- [ ] Implementar service de requisição POST para banho

**Comment by LeoSilvaGomes** [comment]
A pontuação dada para essa issue em relação ao back foi de 2
![image](https://user-images.githubusercontent.com/61520601/134259227-cca8b759-048a-445e-983e-7cd2fa940fd7.png)
