### ISSUE TITLE
Registro de medicamentos

### ISSUE THREAD

**Issue by daniso123** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#118]
## Descrição

Eu como usuário desejo registrar um medicamento para realizar o controle dele

## Critérios de Aceitação:

- [x]  service de requisição POST criado e funcionando
- [x] Cadastro de medicamento criado e funcionando 

## Tarefas:

- [x] Criar model de medicamento
- [x] Disponibilizar endpoint para registro de novos medicamentos a determinado pet
- [ ] Criar página de cadastro de medicamentos
- [x] Implementar service de requisição POST para medicamento

**Comment by LeoSilvaGomes** [comment]
A pontuação dada para essa issue foi de 3
![image](https://user-images.githubusercontent.com/61520601/133174235-78fba623-070f-4cdd-8379-94b125226847.png)

**Comment by LeoSilvaGomes** [comment]
A pontuação dada para essa issue em ralação ao front foi 3
![image](https://user-images.githubusercontent.com/61520601/134259377-0874766a-3367-4f4f-8c09-64fb4ee89906.png)
