### ISSUE TITLE
Registro das vacinas

### ISSUE THREAD

**Issue by lorranyoliveira** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#124]
## Descrição
Eu como usuário desejo registrar as vacinas que o pet tomou para manter o dados atualizados.

## Critérios de Aceitação:
- [ ] Possuir model de vacina.
- [ ] Possuir endpoint para registro de vacinas de um determinado pet.
- [ ] Possuir página de registro de vacina.
- [ ] Possuir service de requisição POST para vacina.

## Tarefas:
- [ ] Criar model de vacina.
- [ ] Disponibilizar endpoint para registro de vacinas de um determinado pet.
- [ ] Criar página de registro de vacina.
- [ ] Implementar service de requisição POST para vacina.

**Comment by KiSobral** [comment]
A pontuação dada para a issue foi de 13
![image](https://user-images.githubusercontent.com/43852963/132267004-93dc03b0-aa4f-47e3-a518-40f65bc749a8.png)

**Comment by LeoSilvaGomes** [comment]
A pontuação dada para a issue foi de 8
![image](https://user-images.githubusercontent.com/61520601/133173472-3da1a722-658c-4294-b39a-de9c063aacf5.png)
