### ISSUE TITLE
Separar issues da sprint 8

### ISSUE THREAD

**Issue by KiSobral** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#137]
## Descrição
Essa issue tem como objetivo abrir a discussão sobre as issues que serão feitas na sprint 7

## Tarefas:

- [ ] Tem comentários sobre as possíveis issues da sprint 7
- [ ] Discussões a respeito da sprint 7

**Comment by KiSobral** [comment]
A pontuação dada para a sprint 2
![image](https://user-images.githubusercontent.com/43852963/132267104-709a1f5d-3d68-4568-94d3-2acf9170af74.png)

**Comment by LeoSilvaGomes** [comment]
Dividas técnicas:
- Registro de vacinas
- Login e Cadastro
- Cadastro de pet

- Documentar sprint 6 e 7
- Adicionar etapa de foto no cadastro de usuário e de pet

**Comment by LeoSilvaGomes** [comment]
- Documentar padrões de projetos utilizados nos códigos feitos
