### ISSUE TITLE
Escrever sobre o design pattern `Chain of Responsibility` (usado no backend e no frontend)

### ISSUE THREAD

**Issue by durvalcarvalho** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#141]
## Descrição

A arquitetura backend for frontend que adotamos utiliza dos conceitos do padrão de projeto Bridge ([link](https://refactoring.guru/pt-br/design-patterns/bridge)). Dessa forma, em nossa documentação, temos que escrever sobre esse padrão de projeto.

## Critérios de Aceitação:

* O documento deve descrever o projeto bridge
* Deve ter diagramas de classes UML 
* Deve contextualizar como o nosso projeto está usando o padrão Bridge

## Tarefas:
- [ ] Ler sobre o padrão
- [ ] Escrever o documento
- [ ] Fazer os diagramas

**Comment by LeoSilvaGomes** [comment]
A pontuação dada para a issue foi de 3
![image](https://user-images.githubusercontent.com/61520601/133173599-f93a98a0-56f6-493d-9e87-d8d1c9bc5ad3.png)
