### ISSUE TITLE
Deploy do backend no heroku

### ISSUE THREAD

**Issue by LeoSilvaGomes** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#144]
## Descrição
Essa issue tem como objetivo fazer o deploy do backend para facilitar a conexão do mesmo com o frontend

## Tarefas:

- [x] Fazer deploy no heroku
- [x] Ter disponivel a porta para acesso a api

**Comment by LeoSilvaGomes** [comment]
A pontuação dada para essa issue foi 3
![image](https://user-images.githubusercontent.com/61520601/133173779-c0031b6a-9ca1-4c49-ba2b-9ce11c67344a.png)

**Comment by viniciusoliveira96** [comment]
Junto ao @durvalcarvalho foi feito o deploy da aplicação BackEnd no Heroku, assim como o CD e o CI.

Segue o link para acesso: [App BackEnd](https://animalesco-backend.herokuapp.com/)
https://animalesco-backend.herokuapp.com
