### ISSUE TITLE
Criação dos protótipos

### ISSUE THREAD

**Issue by KiSobral** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#34]

**Comment by KiSobral** [comment]
A pontuação dada para a issue foi de 5
![image](https://user-images.githubusercontent.com/43852963/129644910-da46aebe-6edc-4e45-97d7-735eb3ff1e9d.png)

**Comment by LeoSilvaGomes** [comment]
A partir dos documentos elicitados, pode se ter mais noção de todas as funcionalidades que poderia compor o aplicativo! Dessa forma foi feito uma pequena lista com todas as informações que poderia haver no aplicativo e sua disposição nas telas.


### Informações

- Informações do usuário
- Informações do pet
- Cada pet
- Banhos agendados
- Medicamentos agendados
- Vacinas agendadas
- Detalhes de consulta do veterinário

### Telas aplicativo Animalesco

- Loading page
- Login
- Cadastro
- Calendário:
    Agendamento de banho
    Agendamento de medicamentos
    Agendamento de vacinas
- Perfil do usuário:
    Nome
    Email
    Foto
    Idade
    Telefone
    Lista de pets
- Perfil do pet:
    - Informações:
         Nome
         Sexo
         Idade
         Peso
         Altura
         Espécie
         Raça
    - Funcionalidades:
         Histórico de idas ao veterinário 
         Calendário
         Gráfico Peso
         Gráfico de Altura

**Comment by LeoSilvaGomes** [comment]
Após esse levantamento das funcionalidades e informações de forma mais grossa, fizemos o protótipo de baixa fidelidade. Para a confecção dessa imagem, foi utilizada um Tablet e em uma chamada de video, ao espelhar a tela do tablet, os participantes podiam dar a opinião sobre o app

![photo_2021-08asdasd-19_20-10-29](https://user-images.githubusercontent.com/61520601/130155664-36e07bd8-7504-4715-8150-cf13cfc96700.jpg)
![photo_2021-06-07_17asdas-22-39](https://user-images.githubusercontent.com/61520601/130155671-2eebf8a6-1c12-46cb-a54a-bc8532b4af93.jpg)

**Comment by LeoSilvaGomes** [comment]
Com as ideias generalistas levantadas no protótipos de baixa fidelidade, conseguimos desenvolver algumas ideias inicias para o protótipo de media fidelidade.

![image](https://user-images.githubusercontent.com/61520601/130156044-ff43f4c9-0439-4466-9326-22211c8d5b49.png)

![image](https://user-images.githubusercontent.com/61520601/130156067-abf7f9d2-50b7-48da-8548-90365e2decf4.png)

**Comment by Rafaelltm** [comment]
> Com as ideias generalistas levantadas no protótipos de baixa fidelidade, conseguimos desenvolver algumas ideias inicias para o protótipo de media fidelidade.
> 
> ![image](https://user-images.githubusercontent.com/61520601/130156044-ff43f4c9-0439-4466-9326-22211c8d5b49.png)
> 
> ![image](https://user-images.githubusercontent.com/61520601/130156067-abf7f9d2-50b7-48da-8548-90365e2decf4.png)

mais algumas ideias para o protótipo de média fidelidade até o momento

![image](https://user-images.githubusercontent.com/54643266/130281531-fdc982ab-90e5-4db0-9a74-555b9e493d83.png)
![image](https://user-images.githubusercontent.com/54643266/130281576-8cbdb3f9-3b0a-45b3-8dc5-0f01ea7fc95a.png)
