### ISSUE TITLE
Criação do documento do `Diagrama de Ishikawa`

### ISSUE THREAD

**Issue by daniso123** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#4]
Fazer um diagrama para levantar as causas-raízes do problema, analisando todos os fatores que envolvem a execução do processo.

**Comment by viniciusoliveira96** [comment]
Diagrama de Ishikawa

![Diagrama de Ishikawa](https://user-images.githubusercontent.com/17971285/127507181-cdc43456-98da-4d9b-b177-407e9976b345.png)
