### ISSUE TITLE
Organização do Kanban da equipe

### ISSUE THREAD

**Issue by KiSobral** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#40]

**Comment by KiSobral** [comment]
A pontuação foi de 2.
![image](https://user-images.githubusercontent.com/43852963/128790597-cd8e6bb5-dc82-43db-96b3-271c90783eb5.png)

**Comment by LeoSilvaGomes** [comment]
Para confecção do Kanban foi utilizado o ZenHub que é uma plataforma que é integrada com o GitHub e é de fácil uso para todos os membros da equipe.

![image](https://user-images.githubusercontent.com/61520601/129973771-b700ad1a-2605-433a-ac84-fbfa16f22ee0.png)
