### ISSUE TITLE
Realizar BPMN da Definição do projeto

### ISSUE THREAD

**Issue by LeoSilvaGomes** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#43]

**Comment by KiSobral** [comment]
Esta issue deve ser trabalhada em cima da branch `18-BPMN`

**Comment by KiSobral** [comment]
A pontuação dada para a issue foi de 3.
![image](https://user-images.githubusercontent.com/43852963/127942155-2d065f61-757f-4bc7-a254-4baa3e8ad4ce.png)

**Comment by durvalcarvalho** [comment]
[bpmn-definicao-do-projeto.pdf](https://github.com/UnBArqDsw2021-1/2021.1_G01_Animalesco_docs/files/6931781/bpmn-definicao-do-projeto.pdf)
![bpmn-definicao-do-projeto-1](https://user-images.githubusercontent.com/31013187/128194049-f278e057-90a4-4c3b-96e2-171717228497.jpg)
![bpmn-definicao-do-projeto-2](https://user-images.githubusercontent.com/31013187/128194057-9b3b5140-46cc-4d65-a97d-d1c58eef6210.jpg)
![bpmn-definicao-do-projeto-3](https://user-images.githubusercontent.com/31013187/128194059-820e1986-70ef-4143-a13c-23d3060d9bee.jpg)
