### ISSUE TITLE
Realizar BPMN da Descrição geral

### ISSUE THREAD

**Issue by KiSobral** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#44]

**Comment by KiSobral** [comment]
Esta issue deve ser trabalhada em cima da branch `18-BPMN`

**Comment by KiSobral** [comment]
A pontuação dada para a issue foi de 5.
![image](https://user-images.githubusercontent.com/43852963/127942879-4389b0d1-f6b8-441b-a995-016a9d6927f6.png)

**Comment by viniciusoliveira96** [comment]
![descricao-geral](https://user-images.githubusercontent.com/17971285/128435071-b581b1ff-8ccb-4a88-bd61-cc587dc9eea1.jpeg)
