### ISSUE TITLE
Realizar BPMN da Daily

### ISSUE THREAD

**Issue by LeoSilvaGomes** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#45]

**Comment by KiSobral** [comment]
Esta issue deve ser trabalhada em cima da branch `18-BPMN`

**Comment by KiSobral** [comment]
A pontuação dada para a issue foi de 2.
![image](https://user-images.githubusercontent.com/43852963/127942741-8f9cdef1-d5d9-4d20-85dd-d84b7f933501.png)

**Comment by daniso123** [comment]
# BPMN da Daily
![Diagrama_Daily](https://user-images.githubusercontent.com/56639683/128229096-84646a8d-c072-4ce0-a0c8-9f397a85c0b1.png)
