### ISSUE TITLE
Realizar BPMN da Sprint review

### ISSUE THREAD

**Issue by LeoSilvaGomes** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#46]

**Comment by KiSobral** [comment]
Esta issue deve ser trabalhada em cima da branch `18-BPMN`

**Comment by KiSobral** [comment]
A pontuação dada para a issue foi de 2.
![image](https://user-images.githubusercontent.com/43852963/127942662-78f05db8-c99d-4770-ae49-17e27a8eb76e.png)

**Comment by lorranyoliveira** [comment]
![Sprint review Diagram](https://user-images.githubusercontent.com/56975965/128250625-e6e138c3-929f-477a-b6de-e5f499266ec5.png)
