### ISSUE TITLE
Realizar BPMN do Planning poker 

### ISSUE THREAD

**Issue by KiSobral** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#47]

**Comment by KiSobral** [comment]
Esta issue deve ser trabalhada em cima da branch `18-BPMN`

**Comment by KiSobral** [comment]
A pontuação dada para a issue foi de 2.
![image](https://user-images.githubusercontent.com/43852963/127942572-efb68463-0bad-4841-964c-968757e46df7.png)

**Comment by Rafaelltm** [comment]
[PlanningPoker.pdf](https://github.com/UnBArqDsw2021-1/2021.1_G01_Animalesco_docs/files/6931969/PlanningPoker.pdf)
![PlanningPoker Diagrama](https://user-images.githubusercontent.com/54643266/128198537-f26e7f22-256c-4bde-835d-e4d95be5e47f.png)
