### ISSUE TITLE
Realizar BPMN da Sprint retrospective

### ISSUE THREAD

**Issue by LeoSilvaGomes** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#48]

**Comment by KiSobral** [comment]
Esta issue deve ser trabalhada em cima da branch `18-BPMN`

**Comment by KiSobral** [comment]
A pontuação dada para a issue foi de 2.
![image](https://user-images.githubusercontent.com/43852963/127942503-f1243e8f-4627-4a6c-b184-f412696d270a.png)

**Comment by KiSobral** [comment]
Segue o diagrama da Sprint Retrospective
![sprint-retrospective-BPMN](https://user-images.githubusercontent.com/43852963/128363607-1f1f9472-f1b4-4bd5-b40a-436c53f3b4ea.jpeg)
