### ISSUE TITLE
 Realizar BPMN do Desenvolvimento

### ISSUE THREAD

**Issue by daniso123** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#49]

**Comment by KiSobral** [comment]
Esta issue deve ser trabalhada em cima da branch `18-BPMN`

**Comment by KiSobral** [comment]
A pontuação dada para a issue foi de 3.
![image](https://user-images.githubusercontent.com/43852963/127942411-adbcfca3-b789-43d4-9893-c8c99b31d265.png)

**Comment by LeoSilvaGomes** [comment]
#### BPMN de desenvolvimento

![BPMN de desenvolvimento Diagram (1)](https://user-images.githubusercontent.com/61520601/128207743-d1e67164-d614-4a15-a912-da7d15db3927.png)

**Comment by LeoSilvaGomes** [comment]
Atualização do BPMN de desenvolvimento
(dívida técnica não é uma task é um dado que será usado para o planejamento da próxima sprint)

![BPMN de desenvolvimento Diagram (3)](https://user-images.githubusercontent.com/61520601/128209885-63c9f028-87c9-4692-98f3-eaeff95f05a0.png)
