### ISSUE TITLE
Documentar o `Brainstorm`

### ISSUE THREAD

**Issue by lorranyoliveira** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#5]
Desde o começo da realização do projeto foi realizado diversos brainstorms para decidir temas, elicitar requisitos e tomar decisões. Porém, nenhuma dessas reuniões, atualmente, está registradas em um documento. Dessa forma, o propósito dessa issue é criar um documento que explique como foi a dinâmica dos brainstormings e quais decisões foram tomadas.

**Comment by KiSobral** [comment]
O Brainstorming já foi realizado em etapas anteriores à disciplina, entretanto, estes não foram devidamente documentados e devem ser resgatados e adaptados os registros para que possamos deixa-los expostos em nossa documentação.
