### ISSUE TITLE
Realizar BPMN da Sprint planning

### ISSUE THREAD

**Issue by LeoSilvaGomes** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#50]

**Comment by KiSobral** [comment]
Esta issue deve ser trabalhada em cima da branch `18-BPMN`

**Comment by KiSobral** [comment]
A pontuação dada para a issue foi de 2.
![image](https://user-images.githubusercontent.com/43852963/127942290-71412a0f-13bc-4a19-a0d1-0d48824232c5.png)

**Comment by JoaoVitorFarias** [comment]
# Sprint planning
![BPMN-sprint-planning](https://user-images.githubusercontent.com/42806627/128092484-cf8c772d-5d63-4d22-8de5-56d808904bbf.png)
