### ISSUE TITLE
Criar o documento `Rich Pictures`

### ISSUE THREAD

**Issue by LeoSilvaGomes** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#6]
## Descrição

Todos os integrantes (com exceção de 1) do grupo deve produzir um Rich Pictures. 
O integrante que não fez o Rich Pictures deve analisar todos os rich pictures, analisá-los e produzir o rich-pictures final, que irá ser o rich-picture do projeto.

# Tarefas
- [ ] Criação dos rich pictures de cada integrante
- [ ] Criação do rich picture final
- [ ] Criação do documento

**Comment by KiSobral** [comment]
O responsável por revisar o documento e fazer a junção em um rich picture geral foi o @durvalcarvalho

**Comment by JoaoVitorFarias** [comment]
![rich-picture](https://user-images.githubusercontent.com/42806627/127399481-e29079bd-41c5-44e9-bad0-092095691149.jpg)

**Comment by durvalcarvalho** [comment]
Rich Ricture do Leonardo Gomes
![rich-picture-leonardo](https://user-images.githubusercontent.com/31013187/127409126-45f61cab-444b-473a-974f-d027f59156b6.png)

**Comment by durvalcarvalho** [comment]
Rich Ricture do Rafael Leão

![rich-picture-rafael](https://user-images.githubusercontent.com/31013187/127409168-5ebe9c59-67cc-416a-8fd0-68e91b541876.jpg)

**Comment by viniciusoliveira96** [comment]
Rich Ricture do Vinicius Oliveira

![Documentos Escaneados(3)_page-0001](https://user-images.githubusercontent.com/17971285/127506898-923f2045-04cb-43d3-b4f9-48c9a7e3f6ba.jpg)

**Comment by daniso123** [comment]
Rich Ricture da Daniela 

![rich-picture-dani](https://raw.githubusercontent.com/UnBArqDsw2021-1/2021.1_G01_Animalesco_docs/6-rich-pictures/assets/pages/rich-pictures/rich-picture-dani.jpg)

**Comment by lorranyoliveira** [comment]
Rich Picture da Lorrany
![Animalesco](https://user-images.githubusercontent.com/56975965/127557575-88ec35c4-a182-41ec-bb4f-8d7344e961ef.png)

**Comment by KiSobral** [comment]
Rich Picture do Hugo
![photo_2021-07-29_21-41-40](https://user-images.githubusercontent.com/43852963/127582856-82129672-231e-4bdb-8a9d-d56d235563df.jpg)
