### ISSUE TITLE
Confeccionar diagrama de pacotes

### ISSUE THREAD

**Issue by KiSobral** [UnBArqDsw2021-1/2021.1_G01_Animalesco_docs#65]

**Comment by KiSobral** [comment]
A pontuação dada para a issue foi de 5.
![image](https://user-images.githubusercontent.com/43852963/128790005-eb16ef74-958d-4439-b66d-16e165ec208e.png)

**Comment by viniciusoliveira96** [comment]
Versão 1 - Diagrama de Pacotes

![Blank diagram](https://user-images.githubusercontent.com/17971285/129061023-ff245b07-947a-4aba-a71a-0018d526df0b.png)
